apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/component: service
  name: react-app-example
spec:
  replicas: 1
  selector:
    matchLabels:
      app: react-app-example
  template:
    metadata:
      labels:
        app.kubernetes.io/component: service
        app: react-app-example
      annotations:
        configmap.reloader.stakater.com/reload: "react-app-example-config"      
    spec:
      containers:
        - name: react-app-example
          image: bhavik0907/react-app:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80
          volumeMounts:
            - name:  react-app-example-config-volume
              mountPath: /usr/share/nginx/html/config.js
              subPath: config.js
              readOnly: true
      volumes:
        - name: react-app-example-config-volume
          configMap:
            name: react-app-example-config
